Do not test on Python 3.8 (which is end-of-life)
It fails inside reportlab with:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/screenplain", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/screenplain/screenplain/screenplain/main.py", line 162, in cli
    main(sys.argv[1:])
  File "/home/runner/work/screenplain/screenplain/screenplain/main.py", line 152, in main
    pdf.to_pdf(screenplay, output, settings=settings)
  File "/home/runner/work/screenplain/screenplain/screenplain/export/pdf.py", line 427, in to_pdf
    doc.build(story)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1062, in build
    self._startBuild(filename,canvasmaker)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1032, in _startBuild
    self.canv = self._makeCanvas(filename=filename,canvasmaker=canvasmaker)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 992, in _makeCanvas
    canv = canvasmaker(filename or self.filename,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/reportlab/pdfgen/canvas.py", line 320, in __init__
    self._doc = pdfdoc.PDFDocument(compression=pageCompression,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/reportlab/pdfbase/pdfdoc.py", line 137, in __init__
    sig = self.signature = md5(usedforsecurity=False)
TypeError: 'usedforsecurity' is an invalid keyword argument for openssl_md5()